### ISSUE TITLE
[Feature request] Support for default + in positive numbers

### ISSUE THREAD

**Issue by LeCuay** [EddieDover/fvtt-party-sheet#29]
# Summary

Basically for modifiers. Negative numbers come with `-` but positive numbers come without sign. Even tho this make sense it kinda breaks the UI consistency.

Obviously this is not needed for **all number fields** so... some kind of marker or flag? A new type maybe?

**Comment by mkahvi** [comment]
Codewise I'd recommend following approach:
```js
const signFormatter = new Intl.NumberFormat('nu', { signDisplay: 'always' });
```
And then whenever you need the signed number, do
```js
signFormatter.format(num);
```
Alternatively instead of `nu` use `game.i18n.lang`, but I personally (possibly falsely) believe `nu` is better.

Of course you could just make trivial function for it also, but this is part of the JS API.

**Comment by EddieDover** [comment]
@LeCuay How about a `showSign` property that can be included alongside the other primary properties of a row object?

```json
{
        "name": "Classes",
        "type": "array-string-builder",
        "header": "show",
        "text": "classes => name - system.levels"
      },
      {
        "name": "STR Mod",
        "type": "direct",
        "header": "hide",
        "showSign": true, // <-- here
        "text": "system.abilities.str.mod"
      },
      {
        "name": "DEX Mod",
        "type": "direct",
        "header": "hide",
        "showSign": true, // <--here
        "text": "system.abilities.dex.mod"
      },
```

Here's a build that implements this. Try it out and let me know what you think. I tried to be as surgical as possible but there's a *lot* going on under the hood so I may need some time to make sure this implementation is solid. 

[fvtt-party-sheet.zip](https://github.com/user-attachments/files/16645632/fvtt-party-sheet.zip)


@mkahvi > Alternatively instead of nu use game.i18n.lang, but I personally (possibly falsely) believe nu is better

Just for my own peace of mind, why do you think the Nauru locale is better for this? IIRC passing undefined as a locale would result in the function using the users default locale. Either way I think opting for a custom function is best for this. The incoming value could be a string, could be a number, could already be signed, etc.

**Comment by mkahvi** [comment]
@EddieDover I seem to recall it was some kind of recommendation in MDN or somewhere but I can't find it.

**Comment by LeCuay** [comment]
> @LeCuay How about a `showSign` property that can be included alongside the other primary properties of a row object?
> 
> ```json
> {
>         "name": "Classes",
>         "type": "array-string-builder",
>         "header": "show",
>         "text": "classes => name - system.levels"
>       },
>       {
>         "name": "STR Mod",
>         "type": "direct",
>         "header": "hide",
>         "showSign": true, // <-- here
>         "text": "system.abilities.str.mod"
>       },
>       {
>         "name": "DEX Mod",
>         "type": "direct",
>         "header": "hide",
>         "showSign": true, // <--here
>         "text": "system.abilities.dex.mod"
>       },
> ```
> 
> EDIT: For simplicity sake I should mention that I've limited this, at the moment, to direct and direct-complex items only.
> 
> Here's a build that implements this. Try it out and let me know what you think. I tried to be as surgical as possible but there's a _lot_ going on under the hood so I may need some time to make sure this implementation is solid.
> 
> [fvtt-party-sheet.zip](https://github.com/user-attachments/files/16645632/fvtt-party-sheet.zip)
> 
> @mkahvi
> 
> > Alternatively instead of nu use game.i18n.lang, but I personally (possibly falsely) believe nu is better
> 
> Just for my own peace of mind, why do you think the Nauru locale is better for this? IIRC passing undefined as a locale would result in the function using the users default locale. Either way I think opting for a custom function is best for this. The incoming value could be a string, could be a number, could already be signed, etc.

Thanks for the quick response @EddieDover 

I can't really try out night releases _right now_ by from Monday I'll let you know
