### ISSUE TITLE
[Bug]: Colspan doesn't work properly

### ISSUE THREAD

**Issue by LeCuay** [EddieDover/fvtt-party-sheet#41]
### What happened?

Images below without and with `colspan` property.

![image](https://github.com/user-attachments/assets/079b3175-de7c-40a8-aa65-78b26010a4e7)
![image](https://github.com/user-attachments/assets/7970958d-8640-4b59-b97c-9f1d294c2eaf)

Currency column set to `"colspan": 5` and the five next column within that row are declared as below with different names each

```json
{
  "name": "Spacer4",
  "type": "span",
  "header": "hide",
  "text": ""
},
```

### What type of foundry hosting were you using?

Local Instance

**Comment by EddieDover** [comment]
I'll investigate. ColSpan was added ages ago and never documented or really used. Sort of a secret feature. And its implementation and use are a bit different than rowspans too.

**Comment by EddieDover** [comment]
I took a quick glance at the code this morning and yeah colspan was never documented because it wasn't used in any official capacity. I think the original intent was to allow for headers to colspan but not data cells. I'd have to go through my chat logs with Emo to really know what was going on at the time.

For now, I'm going to close this issue and re-create as a feature request.  Unfortunately I'm not exactly sure when I'll be able to focus on it, it might be a bit complicated to introduce.
